### ISSUE TITLE
Error while doing inference on resized PNG image

### ISSUE THREAD

**Issue by ymcki** [ankanbhunia/PIDM#17]
I can successfully run inference with a 800x1280 PNG image generated by stable-diffusion-webui with the following python script:

----------------
from predict import Predictor
obj = Predictor()

img_path = "full.png"

obj.predict_pose(image=img_path, sample_algorithm='ddim', num_poses=1, nsteps=50)
----------------

However, the image generated seems to be not in the right aspect ratio.

From you example, I found that the sample image is 1080x1440. So I used gimp to crop a 540x720 and export PNG with default parameters. Then I changed the file name to the new PNG and run inference again. However, I am getting this error:

Traceback (most recent call last):
  File "/tank/ai/PIDM/pose.py", line 9, in <module>
    obj.predict_pose(image=img_path, sample_algorithm='ddim', num_poses=1, nsteps=50)
  File "/tank/ai/PIDM/predict.py", line 51, in predict_pose
    src = self.transforms(src).unsqueeze(0).cuda()
  File "/tank/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/tank/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tank/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 270, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/tank/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 360, in normalize
    return F_t.normalize(tensor, mean=mean, std=std, inplace=inplace)
  File "/tank/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py", line 940, in normalize
    return tensor.sub_(mean).div_(std)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

What went wrong? Thanks a lot in advance.

**Comment by ankanbhunia** [comment]
It seems that your image has 4 channels. To confim, load the image in python and check it's shape. 
np.array(Image.open("img.png")).shape

**Comment by ymcki** [comment]
Thank you very much for your prompt reply. It does indeed have four color channels. I removed the extra color channel with gimp by

Layer > Transparency > Remove Alpha Channel

Now it works.
