### ISSUE TITLE
about Train.py

### ISSUE THREAD

**Issue by ILLLLUSION** [ankanbhunia/PIDM#53]
This code cannot be run using Windows system, right?

**Comment by ILLLLUSION** [comment]
i got a ImportError like this 
NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "testfile.py", line 7, in <module>
    from config.diffconfig import DiffusionConfig, get_model_conf
  File "D:\Myresearch\Person_Image_Synthesis\PIDM\config\__init__.py", line 1, in <module>
    from .diffconfig import *
  File "D:\Myresearch\Person_Image_Synthesis\PIDM\config\diffconfig.py", line 3, in <module>
    from tensorfn.config import (
  File "D:\StudyTools\Anaconda\envs\diffusion\lib\site-packages\tensorfn\config\__init__.py", line 1, in <module>
    from tensorfn.config.config import (
  File "D:\StudyTools\Anaconda\envs\diffusion\lib\site-packages\tensorfn\config\config.py", line 9, in <module>
    from pydantic import (
ImportError: cannot import name 'ArbitraryTypeError' from 'pydantic' (D:\StudyTools\Anaconda\envs\diffusion\lib\site-packages\pydantic\__init__.py)
How to solve?

**Comment by ankanbhunia** [comment]
I haven't tried to run it on windows systems. Sorry can't help on that. Maybe try using wsl?

**Comment by ILLLLUSION** [comment]
> I haven't tried to run it on windows systems. Sorry can't help on that. Maybe try using wsl?

I have solved this error, the pytantic version is too high, but now I only have a gpu, how can I modify the code so that it can start training? Thank you very much for your patient reply.
